### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by badsyntax** [jtangelder/sass-loader#105]
Hi there

I am facing a problem with sharing sass variables across different require() calls. I am appending values to a list variable and I need that variable to be shared between different SCSS modules.

A real world scenario is attempting to a "import-once" function that prevent CSS from being output more than once:

``` scss
// _functions.scss
$imported-once-files: () !default;

@warn $imported-once-files; // debug

@function import-once($filename) {
  @if index($imported-once-files, $filename) {
    @return false;
  }
  $imported-once-files: append($imported-once-files, $filename) !global;
  @return true;
}
```

You cannot use such an approach with sass-loader as each require() call is completely contained from other require() calls, thus `$imported-once-files` is reset with each require() call. I think the only way to resolve this issue to load all component files with sass and have only one entry point require('app.scss') call. 
I'm hoping I'm making sense! Do you have suggestions on how I could make variables global across different require() calls?
Thanks!
