### ISSUE TITLE
Nested partials appear to be included in output.

### ISSUE THREAD

**Issue by danpantry** [jtangelder/sass-loader#235]
I'm using `bootstrap-sass` in my project. In order to add bootstrap-specific configuration, I've created a partial called `_bootstrap.scss` which includes `bootstrap-sass` after setting an environment variable:

`_bootstrap.scss`
````scss
$bootstrap-sass-asset-helper: true;
// The following is a partial
@import '~bootstrap-sass/assets/stylesheets/bootstrap';
````

This is then `@import`ed from files that may consume bootstrap mixins - for example, a control that uses a grid.

`layout.scss`
````scss
@import '../assets/styles/bootstrap';
.logoContainer {
  @include make-md-column(3);
  padding: 10px;
}
````

It's not used anywhere else.

However, my rendered result appears to be including the *entire* bootstrap css in the result - even though I'm including a partial. I would only really expect the result of the mixins to be exported.

I'm not sure if this is a bug in sass-loader, node-sass or if I'm doing something wrong, but I figured it would be best to ask.
