### ISSUE TITLE
Nested Import broken

### ISSUE THREAD

**Issue by Huxpro** [jtangelder/sass-loader#245]
According to <http://sass-lang.com/documentation/file.SASS_REFERENCE.html#nested-import>

```scss
#main {
  @import "example";     // .example { color: red }
}
```
would compile to

```scss
#main .example {
  color: red;
}
```

But with sass-loader@3.1.1 and style, css loaders, I got code like this: 

```html
<style>
.example {
  color: red
}
</style>
<style>
#main { }
</style>
```

It seems like sass-loader passes every `@import` to webpack directly but forget to take nested import in consideration?
