### ISSUE TITLE
Can't import a .sass module from an .scss module

### ISSUE THREAD

**Issue by jcreamer898** [jtangelder/sass-loader#73]
Because of...

https://github.com/jtangelder/sass-loader/blob/master/index.js#L128

I cannot import a `.sass` module within an `.scss` module. 

I have something like this...

```css
// main.scss
@import "_vars";

.element { color: $color; }
```

```css
// some/where/else/_vars.sass
$color: "red"
```
